### ISSUE TITLE
Umbrella: Manage PoC

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#106]
This is an umbrella issue to track completion/progress of the [PoC project](/docs.google.com/document/d/1Fo2curwyplVy2ThNqBEq3oZmuyzVpnBh1j9Xz_qRanU/edit#): 

The idea is to keep a checklist of issues here, feel free to add todos or link issues here
(we can also add these to [a project](https://github.com/auth0/cosmos/projects/1) to get a better feel of priorities). 

⏲ Our deadline is **15 Feb**.
  
### 💎 Screens: 

([Sketch file](https://www.dropbox.com/s/t9i66x2cgn58bkg/cosmos-poc-v04.sketch?dl=0))

- [x] Client list
- [x] Create client (modal)
- [x] Client detail 
- [x] Addons tabs (removed from the PoC)
- [x] Advanced tab (not in sketch) but easily mockable in code

### Components:

- [x] Have basic skeleton for each page and tabbed pages (https://github.com/auth0/cosmos/issues/110)
- [ ] Here's the component inventory: https://github.com/auth0/cosmos/issues/39

### Documentation: 

- [x] Pivot docs to markdown files https://github.com/auth0/cosmos/issues/107
- [ ] Add getting started guide
- [ ] Finish documentation of all the components (break down further)
- [ ] Add icon search

### Packaging:

- [ ] Change the folder structure to a monorepo (yarn workspaces): https://github.com/auth0/cosmos/issues/1
- [ ] Publish design tokens as a library cosmos-tokens@0.0.1
- [ ] Publish cosmos@0.0.1
- [ ] Publish cosmos-preset@0.0.1

### Demo: 

- [ ] Plan a live code example (https://github.com/auth0/cosmos/issues/108)

### Tests: 
- [ ] Snapshot testing
- [ ] Automate visual snapshots, this is more of a manual testing approach https://github.com/auth0/cosmos/issues/15
- [ ] Add linting for component structure. (Look for things like `description`, `styledComponent`, `defaultProps`, `propTypes`, can also be done manually for some time)
- [ ] Add warnings for hardcoded values that should be in tokens
- [ ] Add tracking for cosmos-preset size

### Misc:
- [ ] Fix continuous deployment https://github.com/auth0/cosmos/issues/44
- [ ] Accessibility story (need research here)
  
 ---

### After the PoC:

- [ ] Do a partial implementation of Cosmos in a product   
- [ ] Do a full components inventory
- [ ] Review our scope and goals for 1.0
- [ ] Estimate a date for 1.0 release
- [ ] Bonus: Account centre PoC (will consider after getting enough progress + confidence with manage.

**Comment by nkohari** [comment]
Closing this now since there's no action to take, but it's here for reference if we need it.
