### ISSUE TITLE
☂️ Layout components

### ISSUE THREAD

**Issue by siddharthkp** [auth0/cosmos#1108]
At the moment Cosmos provides a set of components but lacks a system to organize elements on the screen.

In order for the Layout system to be considered "done" we need to solve these issues:

- [x] #1111 Row Layout
- [x] #1112 Column Layout
- [ ] #1113 Stack Layout
- [x] #1114 Gallery Layout
- [x] #1115 Page Layout
- [ ] ~#1116 Toolbar layout~ *replaced by StackLayout*
- [ ] ~#1236 Decide how to aproach an app frame or chrome~ *todo after v1*
- [x] Add optional margin helper to components
- [ ] #1117 Layout Guidelines
- [ ] Define tokens for spacing in layouts

Since each component is isolated from the other, we can and should release them separately as soon as we are confident that they prove to build Manage UI.

**Comment by andresgalante** [comment]
Related to this issue are:
#1111 
#1112
#1113
#1114
#1115
#1116
#1117

**Comment by siddharthkp** [comment]
@andresgalante Feel free to edit the original issue and add all you want

**Comment by francocorreasosa** [comment]
@andresgalante do we have something to update here?
