### ISSUE TITLE
📋 PoC: Review

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#190]
## Tasks
- [x] Merge open PRs
- [x] Review this list together to prioritize
- [x] Assign tasks to each team member
- [x] Plan for Demo
---

## Code:

⭐️ Critical
💅 Polish UI
📖 To Document
[no icon] Normal to-do
🚫 Skip for now

---
## Documentation

*( dibs: @landitus, @siddharthkp  )*

- [x] ⭐️Bug: In the `Switch` component, the `on` prop switcher in props table doesn't affect the example.
- [ ] ⭐️Bug: In the `Button` component, the example in the playground doesn't react on hover.
- [ ] ⭐️💅Polish copy code button in playground and workflow (add tooltip and feedback)
- [ ] ⭐️Automatically generated playground code should look more like "prettier": each prop in a separate line. wdyt @siddharthkp ?
- [ ] ⭐️Changes names of components in sidebar and titles to human friendly or Title Case
- [x] ⭐️Fix handling of strings in prop tables (WIP: https://github.com/auth0/cosmos/issues/157 @siddharthkp)
- [ ] Typography elements: paragraph, heading, links are not documented.
- [ ] Add link to /docs in the sidebar (under getting started) How can we link to custom md pages?
- [ ] 📖Add Principles and write introduction to the project in /docs  
- [ ] 📖Check that all component pages have @ include line  
- [ ] 📖Check that all component pages have Playground/Props table
- [ ] 📖Check that all component pages have component description
- [ ] 🚫Add back **DefaultProps** to the props table 🤔 
- [ ] 🚫Mark required props with * on props table
- [x] Component page: Enlarge the title https://github.com/auth0/cosmos/pull/211
- [x] Bug: Temporary fix the styles that `<pre>` cascades when wrapping the livepreview https://github.com/auth0/cosmos/pull/219
- [x] Fix CSS width of props table to fit the parent container
- [x] Make props table closer to the playground https://github.com/auth0/cosmos/pull/211

## Manage PoC
*( dibs: @nkohari )*
- [ ] ⭐️Add url for each Tab and link each button from Client Table to a tab
- [x] ⭐️Add Tooltips to the Action Input actions. They should be required. https://github.com/auth0/cosmos/issues/193
- [ ] ⭐️💅Polish visuals for the Clients Table. Add more rows.
- [x] ⭐️Add icons to Connections Table
- [ ] 💅Mockup Danger Zone: maybe do a local component with the Delete client part
- [ ] 🚫Mockup saving pattern: When save button is clicked, the loading and success states are displayed. The success notification is shown.
- [ ] 🚫When clicking on a uneditable field with copy actions, the text value is automatically selected. Is this logic part of the product/ or an onClick action? 
- [x] Add icons to Connections tab table #204 
- [x] Bug: change Client secret field to use a input with a masked value instead of password. #185 #205
- [x] Bug: Fix color fo selected menu item in Sidebar @nkohari 
- [x] Add correct icons to each menu item in Sidebar @nkohari
- [x] Add Clients page contents (WIP: https://github.com/auth0/cosmos/pull/197)
- [x] Add Advanced tab contents
- [x] Mockup **Application Header** https://github.com/auth0/cosmos/pull/209
- [x] Mockup **sticky scroll** for Sidebar and Application Header https://github.com/auth0/cosmos/pull/209
- [x] Add Connections tab contents

## Overview
- [ ] ⭐️Change how buttons are displayed: Remove state for all buttons, but add one example labeled Buttons state to show the button animation. @landitus
- [ ] ⭐️Add meaningful labels to each button. @landitus
- [ ] ⭐️💅Fix design and alignment of navigation/icons for Docs, Demo, etc. @landitus

#### Button
*(dibs: @beneliflo )*
- [x] ⭐️💅Bug: the **icon button** has weird padding on the right
- [ ] ⭐️💅The **icon button** icon should be colored like the link (not black) and be smaller
- [ ] 💅The **link button** should be colored like the link (not black)
- [ ] Add the `size` enum prop (default|large)
- [ ] Add examples for default|large buttons in Documentation
- [ ] Add examples for default|large buttons in Overview
- [ ] [Maybe solved] Bug: the **button with icon** is taller (1|2px) than the regular button
- [ ] 🚫Should the `default` state for buttonStyle be documented?
- [ ] 🚫The playground should allow to use a select input to change the buttonStyle props.
- [ ] 🚫Convert primary, transparent, destructive and link to enum `buttonStyle` prop. 
- [ ] 🚫What about `on_____` props?
- [x] Let's roll back and remove the primaryAlt prop. We are sticking with one primary button (the light blue) https://github.com/auth0/cosmos/issues/187

#### Form 
*(dibs: @siddharthkp)*
- [ ] ⭐️Form Actions: Design Rollback. Remove destructive action button.
- [ ] ⭐️💅Bug: Fix spacing in horizontal form.
- [ ] ⭐️💅Form Actions: Add CSS to space out buttons. https://github.com/auth0/cosmos/pull/213
- [ ] ⭐️💅Form helper text: Should use Link Component? Link style should match the link component
- [ ] 🚫Form helper text: Review API
- [x] Docs: Add Field error example to show error messages and state. https://github.com/auth0/cosmos/pull/212
- [x] Add alignment prop to allow for different layouts (default: horizontal|vertical|inline) https://github.com/auth0/cosmos/issues/158
- [x] Docs: Add playground and props table. Remove first example if redundant https://github.com/auth0/cosmos/pull/212
- [x] Docs: Add titles (h?) to each example to identify its purpose. https://github.com/auth0/cosmos/pull/221
- [x] Form Actions: Design Rollback. Change Form Actions to reflect actual design: remove line and top padding. https://github.com/auth0/cosmos/pull/215
- [x] Form Actions: does it go inside the Fieldset? I documented that it should go outside the form actions.

#### TextInput 
- [ ] What about the masked input?
- [ ] 💅Code text should be smaller than regular text (12/13px)
- [ ] 📖Docs: Remove the error example (it's already documented in the Form)

#### TextArea
- [ ] ⭐️💅Fix long code text (Advanced tab) where the text is not wrapping
- [ ] 💅Code text should be smaller than regular text (12/13px)
- [ ] 📖Docs: in "Length of TextArea, change value of small textarea to `3`
- [ ] 📖Docs: Remove the error example (it's already documented in the Form)
- [ ] 📖Docs: `onChange` prop doesn't appear in the props table 
- [ ] 🚫Add ability to have copy action (🤔 won't work with actual design)

#### ActionInput 
- [ ] ⭐️💅Bug: Fix overlap of long text and icons
- [ ] ⭐️💅Fix CSS spacing between actions
- [ ] ⭐️💅Fix CSS: Icon color should be the link color (Blue)
- [ ] 📖Document the Action Input component: we should put an example in the TextInput docs.
- [ ] 🚫Limit to 3 actions

#### Select 
- [x] Add playground and props table
- [x] `DefaultSelected` prop is not working. #180 #210
- [x] ~~Docs: Maybe we need to add the helper, error and field to the Component. Also relates to #177~~

#### Code
- [x] Document the code as an inline component inside the Paragraph component, so it has context. https://github.com/auth0/cosmos/pull/211

#### Icon
(dibs: @nkohari )
- [x] Document it
- [x] Add available icons from library to Documentation
- [x] Check spacing/canvas before merging

#### Heading  
- [ ] Document it

#### Paragraph 
- [ ] Document it
- [ ] Should be a `p` element (block element)
- [ ] Should have a margin-bottom

#### Link 
- [ ] Document it

#### Tabs
- [x] 📖Add playground and props table. https://github.com/auth0/cosmos/pull/225 @landitus
- [x] 📖Remove first example (will be redundant) https://github.com/auth0/cosmos/pull/225 @landitus
- [x] 📖~~The prop `selected` is not documented https://github.com/auth0/cosmos/pull/225~~ @landitus

#### Modal
- [x] Merge and review API (WIP: https://github.com/auth0/cosmos/pull/189 <img src="https://avatars1.githubusercontent.com/u/1576?s=20"/> @nkohari)
 
#### Switch
- [x] ⭐️💅Fix alignment with label in Field #226  
- [x] 💅Fix text style for Label to use the uppercase style #226

#### Tooltip
- [ ] 📖The prop `content` is not documented
- [ ] 🚫Convert `top` and `bottom` props into enum `position`
- [ ] 🚫Should `children` be a prop in the props table to show you can wrap any component?

#### Empty State
- [ ] 💅Review the design: match color of icon to design (should be light blue)
- [ ] 🚫Use button large with primaryAlt for main action.

#### Spinner
- [ ] 🚫Review design: This component should be the main spinner used for loading pages (Auth0 logo inside a rotating spinner). 

---

## Pending components
- [ ] Heading 
- [ ] Paragraph 
- [ ] Breadcrumbs
- [ ] Link (dibs: @siddharthkp)
- [ ] Page Header (WIP: @beneliflo)
- [ ] 🚫Notification
- [ ] 🚫Codeblock
- [ ] 🚫Permissions checkboxes
- [x] List (WIP: https://github.com/auth0/cosmos/pull/191 + https://github.com/auth0/cosmos/pull/192)
- [x] Well (Gray box to put forms into) (WIP: @landitus https://github.com/auth0/cosmos/pull/195)

## Tokens
- [ ] Decide if we change strategy before or after the deadline. https://github.com/auth0/cosmos/pull/176#issuecomment-361117604

**Comment by siddharthkp** [comment]
Need more context for some items under documentation, adding 🤔 to them

**Comment by siddharthkp** [comment]
props table might not make sense for all compound components. 

Example: `Form` has no customisation props, but has a bunch of options for children. Not sure these can be documented in the prop table. I'd like the examples to do a good job of explaining the use.

**Comment by landitus** [comment]
> Documentation
> Add back the Default value to the props table

I recall I deleted 🤭 the default value for each prop (defaultProps) in the props table. I think we could added back and fix the css of the table so that it doesn't break when the rows are too long.

**Comment by landitus** [comment]
> Action Input
> Document the Action Input component

> Action input is an internal component, we don't want others to use it. Might be useful to have a hidden section in the documentation for us

Interesting idea. My initial argument comes from the fact that this behaviour is not documented. Should we document the `actions` prop in `InputText` and add an example usage?

**Comment by landitus** [comment]
> Form
> Docs: Add playground and props table.
> 
> prop table might not make sense for some compound components.
> 
> Example: Form has no customisation props, but has a bunch of options for children. Not sure these can be documented in the prop table. I'd like the examples to do a good job of explaining the use.

Form will have the layout prop, but I see your point. My concern is about not showing the API of the children components: Form.Actions, Form.Fieldset, Form.Group, etc. Why wouldn't we show the API for these?

**Comment by siddharthkp** [comment]
>  > Action input is an internal component, we don't want others to use it. Might be useful to have a hidden section in the documentation for us

> Interesting idea. My initial argument comes from the fact that this behaviour is not documented. Should we document the actions prop in InputText and add an example usage?

Yep, I think that's the way to go.

> Form will have the layout prop, but I see your point. My concern is about not showing the API of the children components: Form.Actions, Form.Fieldset, Form.Group, etc. Why wouldn't we show the API for these?

We should, what would be the best way? 🤔

- We can add them to the sidebar inside a category
OR
- We can add multiple playground + prop tables to Form's documentation

**Comment by landitus** [comment]
Let's give it a shot in our current docs and see how it looks

**Comment by siddharthkp** [comment]
> Form Actions: Design Rollback. Remove destructive action button.

Completely remove it? 😮 Are we bringing danger area back?

**Comment by landitus** [comment]
Ja, yes 😓
