### ISSUE TITLE
☂️ Fixes for Documentation

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#889]
Here's a summary of visual enhancements and bugs for the docs, in order of importance:

### Bugs
- [x] Documentation search is broken https://github.com/auth0/cosmos/issues/775
- [x] `Install guide` is always selected in Docs navigation https://github.com/auth0/cosmos/issues/667
- [x] Linking in documentation keeps the scrolling position between pages. https://github.com/auth0/cosmos/issues/644 This is not yet fixed so here it is again. 

### Enhancements
- [ ] Remove hash # from URLs in documentation https://github.com/auth0/cosmos/issues/659 as it breaks linking from places like Slack and other apps. This is also important as links should be immutable to be accessed from old messages and references.
- [ ] Add Top Navigation bar to storybook. https://github.com/auth0/cosmos/issues/781 This is to keep a consistent nav between these sections of the docs.
- [x] Remove dismissable from the Unstable alerts in docs https://github.com/auth0/cosmos/issues/696
- [ ] Make Overview and Playground full-width in Docs https://github.com/auth0/cosmos/issues/780
- [x] Docs: Navigation isn't responsive (top bar) https://github.com/auth0/cosmos/issues/883
